version: '3'

services:
    postgres: 
        image: postgres:latest
        container_name: postgres-web-shoping
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        volumes:
            - ./application/.postgres-data:/var/lib/postgresql/data


volumes:
    .postgres-data:

